<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cancel</name>
   <tag></tag>
   <elementGuidId>ac7464bf-b592-4df2-bf5c-c199d749493e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div/div[2]/div[2]/div[2]/div/div/div[3]/div[4]/div/div/div/div/span/div/div/div/div[5]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>89ff7d56-0754-4571-97b7-b707c0d8c6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-menu-list-item</value>
      <webElementGuid>c34b95b8-794a-4f7c-b5ce-dae718cd2ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>8a05982d-4841-4859-af2d-36c3e140dcc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;row m-0&quot;]/div[@class=&quot;side-menu&quot;]/div[@class=&quot;wrap-all-the-things&quot;]/div[@class=&quot;col-12 px-0&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;row dashboard-container m-0&quot;]/div[@class=&quot;col-lg-9 col-12 p-0 dashboard-left-container&quot;]/div[1]/div[@class=&quot;dashboard-appointments-view-table ml-3 mt-4 mr-3&quot;]/div[@class=&quot;appointments-view-table-cell&quot;]/div[1]/div[@class=&quot;dashboard-appointments-table-container&quot;]/div[@class=&quot;dashboard-appointments-table-content d-flex pb-2&quot;]/div[@class=&quot;d-flex align-items-center col-md-2 justify-content-end&quot;]/span[@class=&quot;d-flex align-items-center col-md-2 justify-content-end&quot;]/div[1]/div[@class=&quot;filter-menu-list transform-style-custom&quot;]/div[@class=&quot;dropdown&quot;]/div[5]/div[@class=&quot;filter-menu-list-item&quot;]</value>
      <webElementGuid>54c58356-a5e9-483d-ba5b-316e1befacfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div[2]/div[2]/div[2]/div/div/div[3]/div[4]/div/div/div/div/span/div/div/div/div[5]/div</value>
      <webElementGuid>ed38a8c9-a964-4043-8d4d-4a23a3c75131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reschedule'])[1]/following::div[2]</value>
      <webElementGuid>86346686-5454-4b82-9770-bef046ba9f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mark No Show'])[1]/following::div[4]</value>
      <webElementGuid>cbdd7c07-bfc2-4d9c-85aa-70a7a1622298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[1]/preceding::div[1]</value>
      <webElementGuid>2bb46b08-8800-4a4c-bbca-79e700b8c29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div/div[5]/div</value>
      <webElementGuid>91bdb5d5-b050-4853-abab-518cdbe3cdfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>26ba3120-87e3-4ee5-a23c-76aaa4fb43fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
