<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Okay</name>
   <tag></tag>
   <elementGuidId>8fec1037-83c5-4406-9726-38ec08461f39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.success-cancellation-modal-footer-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Okay']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a1daedab-7205-4a6e-96f4-cc305254d143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>success-cancellation-modal-footer-btn</value>
      <webElementGuid>977bf978-5ddf-4f3b-a696-e5f97d7309e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Okay</value>
      <webElementGuid>6bae9aca-f068-47ed-8411-43a510d36241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper&quot;]/div[@class=&quot;MuiPaper-root MuiDialog-paper jss81 MuiDialog-paperScrollPaper MuiDialog-paperWidthSm MuiPaper-elevation24 MuiPaper-rounded&quot;]/div[@class=&quot;success-cancellation-modal-container&quot;]/div[@class=&quot;success-cancellation-modal-footer&quot;]/div[@class=&quot;success-cancellation-modal-footer-btn&quot;]</value>
      <webElementGuid>86e27388-67ec-421f-8d0f-af2f76b3df9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Okay']/parent::*</value>
      <webElementGuid>0a7de636-e750-48ab-af2b-94c65a6f4395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div/div/div[4]/div</value>
      <webElementGuid>18676e45-17a1-4edd-8ffa-471d9fa36129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Okay' or . = 'Okay')]</value>
      <webElementGuid>67c694c4-a4b7-4cda-8ab5-308ae2207f5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
