<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Number_patient_no</name>
   <tag></tag>
   <elementGuidId>f782b344-c773-465e-b346-943911c55e65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;patient_no&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='patient_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be91ca2d-380b-4a30-9729-1cd072ec1a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>21f30295-e5e5-47fa-ba65-20166752a0b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-input</value>
      <webElementGuid>7b274705-cd8a-4563-825f-2e111c91a8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile Number</value>
      <webElementGuid>2cb486c7-62a8-429b-bdc4-2247aaef4c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>22642c2e-611d-4bef-bdb5-8c0acd1db385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>patient_no</value>
      <webElementGuid>d31871ba-5256-453f-ab77-838f7d4df599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade modal show&quot;]/div[@class=&quot;modal-dialog physical-consult w-100 modal-lg modal-dialog-centered modal-dialog-scrollable&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;pc_modal_body pc_scroll modal-body&quot;]/div[@class=&quot;container col-12 ml-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 px-4&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-10 m-auto&quot;]/section[1]/div[@class=&quot;row mt-2&quot;]/div[@class=&quot;col-12 mt-2 mb-4 text-center&quot;]/form[1]/section[@class=&quot;patient-details-form-container&quot;]/div[@class=&quot;row mt-3 d-flex flex-lg-row flex-column align-items-start justify-content-start&quot;]/div[@class=&quot;col-lg-6 col-12 patient-form-item&quot;]/div[@class=&quot;input-group-prepend phone_width&quot;]/div[@class=&quot;search-wrapper&quot;]/div[@class=&quot;input-holder&quot;]/input[@class=&quot;search-input&quot;]</value>
      <webElementGuid>ea57b2f9-43e3-45b0-a425-408a6b71730f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='patient_no']</value>
      <webElementGuid>b9cfc034-5c6d-4cee-84d0-3102f48504ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/input</value>
      <webElementGuid>a780dfd1-1f0c-408c-8afb-eae5ab36e6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Mobile Number' and @name = 'patient_no']</value>
      <webElementGuid>48a1478f-0d9b-44a6-aa29-83cdff80f02a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
