<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login to Virtual Clinic_OTP-input</name>
   <tag></tag>
   <elementGuidId>ded534a9-eded-4cfa-8978-24d7a24b2eb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OTP-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OTP-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8680e749-247d-463e-8bb4-a31071146407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>58cdc3a2-39d5-4b88-8a9d-abb9b6b72dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>my-helper-text</value>
      <webElementGuid>f2ed527a-dacb-4dff-a154-030e37767b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OTP-input</value>
      <webElementGuid>72a42d9d-caf6-4db6-a446-0b72c9034a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Phone Number</value>
      <webElementGuid>e86d2417-545d-4a73-988a-ab7bf240ce64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3af4f52d-5195-4605-b286-ac6dee9a54b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>22d63ed8-c37b-4bb6-8c6a-552438f40d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiFilledInput-input MuiInputBase-inputHiddenLabel MuiFilledInput-inputHiddenLabel MuiInputBase-inputAdornedStart MuiFilledInput-inputAdornedStart MuiInputBase-inputMarginDense MuiFilledInput-inputMarginDense</value>
      <webElementGuid>f338dff1-602a-4878-8567-73f7754acb33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OTP-input&quot;)</value>
      <webElementGuid>3e28005b-d718-454f-b274-d19c02cc1eab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OTP-input']</value>
      <webElementGuid>d71d307d-c999-456a-a833-6a969b43494c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div[2]/div/div/div/div/div/div/form/div/div/input</value>
      <webElementGuid>ea230371-8899-49d8-b7e4-54c38594b204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c0851c93-b5f2-476f-9799-21b6a23e8676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'OTP-input' and @placeholder = 'Enter Phone Number' and @type = 'text']</value>
      <webElementGuid>b9d13eaf-4834-4d19-b7c5-2fbcc7353961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
