<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Sai</name>
   <tag></tag>
   <elementGuidId>430deac6-a115-41c5-bfa4-7ee6204015a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.searched_item_text > h5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile Number'])[1]/following::h5[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>e451edf5-dd86-44b3-b1e0-eb09336fb87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sai</value>
      <webElementGuid>0724a76f-074f-4313-8d20-2d808b2f7f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade modal show&quot;]/div[@class=&quot;modal-dialog physical-consult w-100 modal-lg modal-dialog-centered modal-dialog-scrollable&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;pc_modal_body pc_scroll modal-body&quot;]/div[@class=&quot;container col-12 ml-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 px-4&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-10 m-auto&quot;]/section[1]/div[@class=&quot;row mt-2&quot;]/div[@class=&quot;col-12 mt-2 mb-4 text-center&quot;]/form[1]/section[@class=&quot;patient-details-form-container&quot;]/div[@class=&quot;row mt-3 d-flex flex-lg-row flex-column align-items-start justify-content-start&quot;]/div[@class=&quot;col-lg-6 col-12 patient-form-item&quot;]/div[@class=&quot;input-group-prepend phone_width&quot;]/div[@class=&quot;search-wrapper isActive&quot;]/div[@class=&quot;searched_value&quot;]/ul[@class=&quot;searched_value_scroll&quot;]/li[1]/div[@class=&quot;searched_item&quot;]/div[@class=&quot;searched_item_text&quot;]/h5[1]</value>
      <webElementGuid>88b3b97d-1137-4286-aae3-7e02f1df4f63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile Number'])[1]/following::h5[1]</value>
      <webElementGuid>1b00fd8f-b4c3-4af2-ba02-80326af0df62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review &amp; Share'])[2]/following::h5[1]</value>
      <webElementGuid>98d0cc8e-9805-4623-8924-b4e2aba726e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Name'])[1]/preceding::h5[1]</value>
      <webElementGuid>518bb763-9311-456d-8d99-69101e1cf511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found'])[1]/preceding::h5[1]</value>
      <webElementGuid>b4fd0e7f-0530-40b7-95ce-154f0010610d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sai']/parent::*</value>
      <webElementGuid>faae78e4-a084-4e1b-bd31-33de1cb08deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/h5</value>
      <webElementGuid>fd3ae4cd-c719-4d9f-a12f-3ed1fc291f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Sai' or . = 'Sai')]</value>
      <webElementGuid>2b7440af-f7f3-477e-961f-1ce01317a3fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
