<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sex_patient_gender</name>
   <tag></tag>
   <elementGuidId>1fdf7542-0669-4cae-b44f-fa4faec1a176</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Male</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Male']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d76f5974-0bf3-4078-982f-1a7a9a804d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>49ef89f5-c8ec-482e-9ca3-52787e39c0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>57d69634-b4d3-431b-bd42-1b7eb8a288ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>e13b15f1-32cf-46b3-8d87-83bee2c8f499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>patient_gender</value>
      <webElementGuid>baa56ab8-0f3a-4e77-8cb7-5a9ee859c28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>3fe8d346-32de-4813-8e71-3d65672e2883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Male&quot;)</value>
      <webElementGuid>bb2ef5e2-82cf-4d6f-b107-ca119d3851fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Male']</value>
      <webElementGuid>23499a99-c269-4046-a841-f2fcd555a585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>4437b35c-b30f-4ba2-a53d-6265298bea82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'Male' and @name = 'patient_gender']</value>
      <webElementGuid>d95d418e-cc58-4880-a845-bb771387ad9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
