<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login to Virtual Clinic_OTP-input</name>
   <tag></tag>
   <elementGuidId>4b0e5897-457a-4faa-9806-dced65d83816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OTP-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OTP-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb4ff6ce-5411-4c89-8e3d-2410260787c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4dcf6993-d418-47a8-8c65-8d6b1f92f542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>my-helper-text</value>
      <webElementGuid>6ef849be-8c18-40b0-880f-bed6e881a4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OTP-input</value>
      <webElementGuid>eb029574-5cc7-4175-88dd-e1bcb7bcee6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Phone Number</value>
      <webElementGuid>9d8522ee-7c35-4ed7-95ca-f22aa87f2652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9eef0b90-1b74-47ae-a6d6-46c709241b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>b62945e4-cea2-4400-b62b-012620a9ce2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiFilledInput-input MuiInputBase-inputHiddenLabel MuiFilledInput-inputHiddenLabel MuiInputBase-inputAdornedStart MuiFilledInput-inputAdornedStart MuiInputBase-inputMarginDense MuiFilledInput-inputMarginDense</value>
      <webElementGuid>6ec6e2a0-57ed-4485-a093-960df6b0d975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OTP-input&quot;)</value>
      <webElementGuid>e52aa849-411a-4f0f-a5d0-ac2c8f42fc09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OTP-input']</value>
      <webElementGuid>583b57cd-02b9-4f35-ab25-1fbdf4c928d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div[2]/div/div/div/div/div/div/form/div/div/input</value>
      <webElementGuid>8ea17cc6-d390-494b-921e-7053b024b559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8e98c943-9283-4a48-87c5-31168bc1351b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'OTP-input' and @placeholder = 'Enter Phone Number' and @type = 'text']</value>
      <webElementGuid>2e84f5eb-2f15-489b-84e1-b52eb156d8cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
