<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Number_patient_no</name>
   <tag></tag>
   <elementGuidId>2df0bdd3-992c-4f22-889c-7be1d0acc973</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;patient_no&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='patient_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8f2f1bd-3cb6-48c3-8f5e-0b5d70fda504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4e868e86-f001-42dc-823e-1c5822c30700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-input</value>
      <webElementGuid>ffe4e722-2e15-438e-85b5-960d31b77beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile Number</value>
      <webElementGuid>33d103f3-4442-46f2-b237-af4614460b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>3de35b65-79bb-4c71-a631-5d00b9e664cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>patient_no</value>
      <webElementGuid>0a59aee7-dc30-4003-a422-d68d06045d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade modal show&quot;]/div[@class=&quot;modal-dialog physical-consult w-100 modal-lg modal-dialog-centered modal-dialog-scrollable&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;pc_modal_body pc_scroll modal-body&quot;]/div[@class=&quot;container col-12 ml-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 px-4&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-10 m-auto&quot;]/section[1]/div[@class=&quot;row mt-2&quot;]/div[@class=&quot;col-12 mt-2 mb-4 text-center&quot;]/form[1]/section[@class=&quot;patient-details-form-container&quot;]/div[@class=&quot;row mt-3 d-flex flex-lg-row flex-column align-items-start justify-content-start&quot;]/div[@class=&quot;col-lg-6 col-12 patient-form-item&quot;]/div[@class=&quot;input-group-prepend phone_width&quot;]/div[@class=&quot;search-wrapper&quot;]/div[@class=&quot;input-holder&quot;]/input[@class=&quot;search-input&quot;]</value>
      <webElementGuid>789867a9-f451-4fbb-aaf3-806664f85c90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='patient_no']</value>
      <webElementGuid>f86215ae-5228-4ed8-8e6a-aa1ebf55f4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/input</value>
      <webElementGuid>c92d4d61-41b1-4ab9-b056-126b68dcae95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Mobile Number' and @name = 'patient_no']</value>
      <webElementGuid>30802b3b-5b3a-49ef-9f39-19c1df2a60d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
